### ISSUE TITLE
iOS jobs

### ISSUE THREAD

**Issue by TNorbury** [TNorbury/music_note#106]
- [x] Verify that ads work

- [x] Verify EU and IDFA messages appear and work
  - [x] Delay app measurement until we have user consent: https://developers.google.com/admob/ios/eu-consent#delay_app_measurement_optional

- [x] Create iOS Firebase project
  - [x] Link iOS admob app to firebase app

- [x] Spotify functionality.

- [x] App icon and splash screen
- [x] splash screen looks weird on some devices

- [x] webview on ios doesn't fit inside of dialog

- [x] Create developer account
