### ISSUE TITLE
Get user consent for ads/tracking/etc

### ISSUE THREAD

**Issue by TNorbury** [TNorbury/music_note#134]
Useful package: https://pub.dev/packages/admob_consent

Related info:
https://support.google.com/admob/answer/9263723?hl=en#policy
https://developers.google.com/admob/android/eu-consent#delay_app_measurement_optional
https://developers.google.com/admob/android/eu-consent

- [x] Create simple lil' website for Music Note, there will be two pages: one that will just be like "coming soon", and another that'll be for our privacy policy

- [x] Link admob to analytics with the consent stuff is implemented.

- [x] Add data and privacy page that has the privacy policy and an option to revoke consent.
